dmiksu/urls.py
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^', include('note.urls', namespace='note')),
]

note/urls.py
from django.conf.urls import url

from note.views import index, regex, git, linux

app_name = 'note'

urlpatterns = [
    url(r'^regex/$', regex, name='regex'),
    url(r'^git/$', git, name='git'),
    url(r'^linux/$', linux, name='linux'),
    url(r'^$', index, name='index'),
]

note/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def regex(request):
    return render(request, 'note/regex.html')


def linux(request):
    return render(request, 'note/linux.html')


def git(request):
    return render(request, 'note/git.html')

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Test{% endblock %}</title>
    {% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
    {% endblock %}
</head>
<body>
<header>
    {% block nav %}
        {% include "nav.html" %}
    {% endblock %}
</header>
    {% block content %}{% endblock %}
</body>
</html>

templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Test{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
<header>
    {% block nav %}
        {% include "nav.html" %}
    {% endblock %}
</header>
<main>
    {% block content %}{% endblock %}
</main>
<footer>
</footer>
</body>
</html>

templates/nav.html
{% load staticfiles %}

<div class="container-menu">
    <nav>
        <ul>
            <li><a href={% url "note:index" %}>home</a></li>
            <li><a href="#">notes</a>
                <ul class="dropdown_menu">
                    <li><a href={% url "note:regex" %}>regex</a></li>
                    <li><a href={% url "note:git" %}>git</a></li>
                    <li><a href={% url "note:linux" %}>linux</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</div>

templates/note/git.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block title %}Git{% endblock %}

{% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static "css/note/content.css" %}">
{% endblock %}

{% block content %}
    <div>
        <br/>
        <input class='hide' type='checkbox' id='g-01'/>
        <label for='g-01'>Git</label>
        <div>Control Version System</div>
        <br/>
    </div>
{% endblock %}

templates/note/linux.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block title %}Linux{% endblock %}

{% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static "css/note/content.css" %}">
{% endblock %}

{% block content %}
    <div>
        <br/>
        <input class='hide' type='checkbox' id='l-01'/>
        <label for='l-01'>Linux</label>
        <div>Operating System</div>
        <br/>
    </div>
{% endblock %}

templates/note/regex.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block title %}ReGeX{% endblock %}

{% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static "css/note/content.css" %}">
{% endblock %}

{% block content %}
    <div>
        <br/>
        <input class='hide' type='checkbox' id='r-01'/>
        <label for='r-01'>ReGeX</label>
        <div>Regular Expressions</div>
        <br/>
    </div>
{% endblock %}